<template>
    <div class="easter-container">
        <h2 class="easter-heading">Joyeuse Pâques!</h2>
        <div class="set">
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/gold-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/blue-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/pink-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/purple-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/gold-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/blue-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/pink-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/purple-easter-egg.png"
            />
            </div>
        </div>
        <div class="set set2">
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/gold-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/blue-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/pink-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/purple-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/gold-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/blue-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/pink-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/purple-easter-egg.png"
            />
            </div>
        </div>
        <div class="set set3">
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/gold-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/blue-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/pink-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/purple-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/gold-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/blue-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/pink-easter-egg.png"
            />
            </div>
            <div>
            <img
                src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/74196/purple-easter-egg.png"
            />
            </div>
        </div>
    </div>
</template>